### ISSUE TITLE
FileModelの名前

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Files#12]
FileクラスはCakePHPのUtilityにあるため、FileModelという名前にしたと思われます。
Attachmentが良い気がします。
https://github.com/cakephp/cakephp/issues/3506

**Comment by kteraguchi** [comment]
Uploadでも良いと思います。

**Comment by kteraguchi** [comment]
cakephp-uploadを利用しているので、Documentのsample見るとAttachmentですね。
http://cakephp-upload.readthedocs.org/en/latest/polymorphic.html

**Comment by kteraguchi** [comment]
https://github.com/NetCommons3/Videos/issues/12
で吸収しましょう。

**Comment by RyujiAMANO** [comment]
TestCaseだけどcakephpにAttachmentクラス発見。
/vendors/cakephp/cakephp/lib/Cake/Test/Case/Model/models.php

**Comment by kteraguchi** [comment]
Attachment使えないですね。
現状UploadFileで作業中なので、情報残しておきます。

**Comment by RyujiAMANO** [comment]
FileMode削除済みなのでCLOSEします
