### ISSUE TITLE
ERDについて

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Files#13]
files_plugins,files_rooms,files_usersの3テーブルについて、
1ファイルを、複数プラグインから利用、複数ルームで利用、複数ユーザーで利用みたいなイメージで使うのでしょうか？
共有設定みたいな機能がある感じかなぁ。。
もくもく会で教えてください。

**Comment by kteraguchi** [comment]
複数プラグインから利用、複数ルームで利用、複数ユーザーで利用しないとのこと。
ERD見直しです。

https://github.com/NetCommons3/Videos/issues/12
で吸収しましょう。

**Comment by s-nakajima** [comment]
ERD検討、龍司さん対応済み。
2015/12/29以降、年末・年始でERDに反映予定
