### ISSUE TITLE
処理内容とメソッド名にずれがある。validateDeletedFiles()

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/Files#8]
validateDeletedFiles()となっているけど、findしてるだけだった。
念のため報告。

https://github.com/NetCommons3/Files/blob/master/Model/FileModel.php#L312

**Comment by akagane99** [comment]
ここに権限チェックが入るから、こうなっているのかも？

**Comment by s-nakajima** [comment]
当ファイルはもうないのでClose
